/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.billingSystem.view;

/**
 *
 * @author Bryan Azuero
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnuCustomer = new javax.swing.JMenu();
        ItmFindCustomer = new javax.swing.JMenuItem();
        ItmCheckIn = new javax.swing.JMenuItem();
        mnuArticle = new javax.swing.JMenu();
        mnuListArticle = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        mnuBilling = new javax.swing.JMenu();
        ItmNewBilling = new javax.swing.JMenuItem();
        mnuConsultation = new javax.swing.JMenu();
        ItmCheckInvoice = new javax.swing.JMenuItem();
        mnuProviders = new javax.swing.JMenu();
        ItmRegisterProvider = new javax.swing.JMenuItem();
        mnuListProvider = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("jMenu6");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("System");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        mnuCustomer.setText("Customer");

        ItmFindCustomer.setText("Find Customer");
        ItmFindCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmFindCustomerActionPerformed(evt);
            }
        });
        mnuCustomer.add(ItmFindCustomer);

        ItmCheckIn.setText("Check In");
        ItmCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmCheckInActionPerformed(evt);
            }
        });
        mnuCustomer.add(ItmCheckIn);

        jMenuBar1.add(mnuCustomer);

        mnuArticle.setText("Articles");

        mnuListArticle.setText("Register");
        mnuArticle.add(mnuListArticle);

        jMenu10.setText("List of Article");
        mnuArticle.add(jMenu10);

        jMenuBar1.add(mnuArticle);

        mnuBilling.setText("Billing");

        ItmNewBilling.setText("New sale");
        mnuBilling.add(ItmNewBilling);

        jMenuBar1.add(mnuBilling);

        mnuConsultation.setText("Consultation");

        ItmCheckInvoice.setText("Check invoice");
        ItmCheckInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmCheckInvoiceActionPerformed(evt);
            }
        });
        mnuConsultation.add(ItmCheckInvoice);

        jMenuBar1.add(mnuConsultation);

        mnuProviders.setText("Providers");

        ItmRegisterProvider.setText("Register provider");
        mnuProviders.add(ItmRegisterProvider);

        mnuListProvider.setText("List of provider");
        mnuProviders.add(mnuListProvider);

        jMenuBar1.add(mnuProviders);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmFindCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmFindCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmFindCustomerActionPerformed

    private void ItmCheckInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmCheckInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmCheckInvoiceActionPerformed

    private void ItmCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmCheckInActionPerformed
        this.setVisible(false);
        FrmCustomer frmCustomer = new FrmCustomer();
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_ItmCheckInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmCheckIn;
    private javax.swing.JMenuItem ItmCheckInvoice;
    private javax.swing.JMenuItem ItmFindCustomer;
    private javax.swing.JMenuItem ItmNewBilling;
    private javax.swing.JMenuItem ItmRegisterProvider;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuArticle;
    private javax.swing.JMenu mnuBilling;
    private javax.swing.JMenu mnuConsultation;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuListArticle;
    private javax.swing.JMenuItem mnuListProvider;
    private javax.swing.JMenu mnuProviders;
    // End of variables declaration//GEN-END:variables
}
